// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crossrefd/sanction/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params           Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Agents           []AgentInfo       `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents"`
	RiskReports      []RiskReport      `protobuf:"bytes,3,rep,name=risk_reports,json=riskReports,proto3" json:"risk_reports"`
	SanctionCases    []SanctionCase    `protobuf:"bytes,4,rep,name=sanction_cases,json=sanctionCases,proto3" json:"sanction_cases"`
	SanctionVotes    []SanctionVote    `protobuf:"bytes,5,rep,name=sanction_votes,json=sanctionVotes,proto3" json:"sanction_votes"`
	ActiveSanctions  []ActiveSanction  `protobuf:"bytes,6,rep,name=active_sanctions,json=activeSanctions,proto3" json:"active_sanctions"`
	FrozenAddresses  []FreezeRecord    `protobuf:"bytes,7,rep,name=frozen_addresses,json=frozenAddresses,proto3" json:"frozen_addresses"`
	ExecutionRecords []ExecutionRecord `protobuf:"bytes,8,rep,name=execution_records,json=executionRecords,proto3" json:"execution_records"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b16eb4659adda320, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetAgents() []AgentInfo {
	if m != nil {
		return m.Agents
	}
	return nil
}

func (m *GenesisState) GetRiskReports() []RiskReport {
	if m != nil {
		return m.RiskReports
	}
	return nil
}

func (m *GenesisState) GetSanctionCases() []SanctionCase {
	if m != nil {
		return m.SanctionCases
	}
	return nil
}

func (m *GenesisState) GetSanctionVotes() []SanctionVote {
	if m != nil {
		return m.SanctionVotes
	}
	return nil
}

func (m *GenesisState) GetActiveSanctions() []ActiveSanction {
	if m != nil {
		return m.ActiveSanctions
	}
	return nil
}

func (m *GenesisState) GetFrozenAddresses() []FreezeRecord {
	if m != nil {
		return m.FrozenAddresses
	}
	return nil
}

func (m *GenesisState) GetExecutionRecords() []ExecutionRecord {
	if m != nil {
		return m.ExecutionRecords
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "crossrefd.sanction.v1.GenesisState")
}

func init() {
	proto.RegisterFile("crossrefd/sanction/v1/genesis.proto", fileDescriptor_b16eb4659adda320)
}

var fileDescriptor_b16eb4659adda320 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x13, 0x77, 0x37, 0xca, 0x74, 0xd5, 0x3a, 0x28, 0x84, 0x82, 0xb1, 0xbb, 0x8b, 0xb2,
	0xa7, 0x84, 0xad, 0x47, 0x41, 0x68, 0xc5, 0x9f, 0xa7, 0x92, 0x4a, 0x41, 0x2f, 0x61, 0x9a, 0xbc,
	0xc6, 0x50, 0x9a, 0x09, 0xf3, 0xa6, 0xa1, 0xf6, 0xec, 0x1f, 0xe0, 0x9f, 0xd5, 0x63, 0x8f, 0x9e,
	0x44, 0xda, 0x7f, 0x44, 0x32, 0xc9, 0xb4, 0x06, 0x1b, 0xf1, 0x36, 0x7c, 0xf9, 0xbc, 0x4f, 0x5e,
	0x1e, 0x5f, 0x72, 0x15, 0x0a, 0x8e, 0x28, 0x60, 0x1a, 0x79, 0xc8, 0xd2, 0x50, 0x26, 0x3c, 0xf5,
	0xf2, 0x1b, 0x2f, 0x86, 0x14, 0x30, 0x41, 0x37, 0x13, 0x5c, 0x72, 0xfa, 0x68, 0x0f, 0xb9, 0x1a,
	0x72, 0xf3, 0x9b, 0xce, 0xc3, 0x98, 0xc7, 0x5c, 0x11, 0x5e, 0xf1, 0x2a, 0xe1, 0xce, 0xe5, 0x71,
	0x63, 0xc6, 0x04, 0x9b, 0x57, 0xc2, 0xce, 0xc5, 0x71, 0x46, 0x7e, 0xcd, 0xa0, 0x42, 0x2e, 0xbf,
	0x9d, 0x91, 0xf3, 0xb7, 0xe5, 0x16, 0x23, 0xc9, 0x24, 0xd0, 0x17, 0xc4, 0x2a, 0x1d, 0xb6, 0xd9,
	0x35, 0xaf, 0x5b, 0xbd, 0xc7, 0xee, 0xd1, 0xad, 0xdc, 0xa1, 0x82, 0x06, 0xa7, 0xeb, 0x9f, 0x4f,
	0x0c, 0xbf, 0x1a, 0xa1, 0x2f, 0x89, 0xc5, 0x62, 0x48, 0x25, 0xda, 0xb7, 0xba, 0x27, 0xd7, 0xad,
	0x5e, 0xb7, 0x61, 0xb8, 0x5f, 0x40, 0xef, 0xd3, 0x29, 0xd7, 0xf3, 0xe5, 0x14, 0xfd, 0x40, 0xce,
	0x45, 0x82, 0xb3, 0x40, 0x40, 0xc6, 0x85, 0x44, 0xfb, 0x44, 0x59, 0x2e, 0x1a, 0x2c, 0x7e, 0x82,
	0x33, 0x5f, 0x91, 0x95, 0xa6, 0x25, 0xf6, 0x09, 0xd2, 0x21, 0xb9, 0xa7, 0xe1, 0x20, 0x64, 0x08,
	0x68, 0x9f, 0x2a, 0xdb, 0x55, 0x83, 0x6d, 0x54, 0xbd, 0x5f, 0x31, 0x84, 0xca, 0x77, 0x17, 0xff,
	0xc8, 0xea, 0xc6, 0x9c, 0x4b, 0x40, 0xfb, 0xec, 0xbf, 0x8c, 0x63, 0x2e, 0xff, 0x32, 0x16, 0x19,
	0xd2, 0x31, 0x69, 0xb3, 0x50, 0x26, 0x39, 0x04, 0x3a, 0x47, 0xdb, 0x52, 0xce, 0xa7, 0x4d, 0x97,
	0x53, 0xb8, 0x36, 0x57, 0xd6, 0xfb, 0xac, 0x96, 0x22, 0xfd, 0x48, 0xda, 0x53, 0xc1, 0x57, 0x90,
	0x06, 0x2c, 0x8a, 0x04, 0x60, 0xf1, 0xf7, 0xb7, 0xff, 0xb9, 0xeb, 0x1b, 0x01, 0xb0, 0x02, 0x1f,
	0x42, 0x2e, 0x22, 0x6d, 0x2d, 0x15, 0x7d, 0x6d, 0xa0, 0x9f, 0xc8, 0x03, 0x58, 0x42, 0xb8, 0x50,
	0x07, 0x10, 0x0a, 0x45, 0xfb, 0x8e, 0xd2, 0x3e, 0x6b, 0xd0, 0xbe, 0xd6, 0x7c, 0xcd, 0xdc, 0x86,
	0x7a, 0x8c, 0x83, 0x77, 0xeb, 0xad, 0x63, 0x6e, 0xb6, 0x8e, 0xf9, 0x6b, 0xeb, 0x98, 0xdf, 0x77,
	0x8e, 0xb1, 0xd9, 0x39, 0xc6, 0x8f, 0x9d, 0x63, 0x7c, 0x76, 0xe3, 0x44, 0x7e, 0x59, 0x4c, 0xdc,
	0x90, 0xcf, 0x3d, 0xfd, 0x0d, 0xef, 0xd0, 0xeb, 0xe5, 0xa1, 0xd9, 0xaa, 0xd6, 0x13, 0x4b, 0xf5,
	0xfa, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xd5, 0x60, 0xd3, 0x72, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExecutionRecords) > 0 {
		for iNdEx := len(m.ExecutionRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExecutionRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.FrozenAddresses) > 0 {
		for iNdEx := len(m.FrozenAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FrozenAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ActiveSanctions) > 0 {
		for iNdEx := len(m.ActiveSanctions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActiveSanctions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SanctionVotes) > 0 {
		for iNdEx := len(m.SanctionVotes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SanctionVotes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SanctionCases) > 0 {
		for iNdEx := len(m.SanctionCases) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SanctionCases[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.RiskReports) > 0 {
		for iNdEx := len(m.RiskReports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RiskReports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Agents) > 0 {
		for iNdEx := len(m.Agents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Agents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Agents) > 0 {
		for _, e := range m.Agents {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RiskReports) > 0 {
		for _, e := range m.RiskReports {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SanctionCases) > 0 {
		for _, e := range m.SanctionCases {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SanctionVotes) > 0 {
		for _, e := range m.SanctionVotes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActiveSanctions) > 0 {
		for _, e := range m.ActiveSanctions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FrozenAddresses) > 0 {
		for _, e := range m.FrozenAddresses {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ExecutionRecords) > 0 {
		for _, e := range m.ExecutionRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Agents = append(m.Agents, AgentInfo{})
			if err := m.Agents[len(m.Agents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskReports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RiskReports = append(m.RiskReports, RiskReport{})
			if err := m.RiskReports[len(m.RiskReports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SanctionCases", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SanctionCases = append(m.SanctionCases, SanctionCase{})
			if err := m.SanctionCases[len(m.SanctionCases)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SanctionVotes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SanctionVotes = append(m.SanctionVotes, SanctionVote{})
			if err := m.SanctionVotes[len(m.SanctionVotes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveSanctions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveSanctions = append(m.ActiveSanctions, ActiveSanction{})
			if err := m.ActiveSanctions[len(m.ActiveSanctions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FrozenAddresses = append(m.FrozenAddresses, FreezeRecord{})
			if err := m.FrozenAddresses[len(m.FrozenAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutionRecords = append(m.ExecutionRecords, ExecutionRecord{})
			if err := m.ExecutionRecords[len(m.ExecutionRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
