// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crossrefd/sanction/v1/params.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	WatchThreshold             uint32           `protobuf:"varint,1,opt,name=watch_threshold,json=watchThreshold,proto3" json:"watch_threshold,omitempty"`
	BlockThreshold             uint32           `protobuf:"varint,2,opt,name=block_threshold,json=blockThreshold,proto3" json:"block_threshold,omitempty"`
	FreezeThreshold            uint32           `protobuf:"varint,3,opt,name=freeze_threshold,json=freezeThreshold,proto3" json:"freeze_threshold,omitempty"`
	RevertThreshold            uint32           `protobuf:"varint,4,opt,name=revert_threshold,json=revertThreshold,proto3" json:"revert_threshold,omitempty"`
	QuorumThreshold            uint32           `protobuf:"varint,5,opt,name=quorum_threshold,json=quorumThreshold,proto3" json:"quorum_threshold,omitempty"`
	UnanimousRequiredForRevert bool             `protobuf:"varint,6,opt,name=unanimous_required_for_revert,json=unanimousRequiredForRevert,proto3" json:"unanimous_required_for_revert,omitempty"`
	EvidenceTtlBlocks          uint64           `protobuf:"varint,7,opt,name=evidence_ttl_blocks,json=evidenceTtlBlocks,proto3" json:"evidence_ttl_blocks,omitempty"`
	VotingPeriodBlocks         uint64           `protobuf:"varint,8,opt,name=voting_period_blocks,json=votingPeriodBlocks,proto3" json:"voting_period_blocks,omitempty"`
	AcceptedRiskSources        []string         `protobuf:"bytes,9,rep,name=accepted_risk_sources,json=acceptedRiskSources,proto3" json:"accepted_risk_sources,omitempty"`
	HighRiskCategories         []string         `protobuf:"bytes,10,rep,name=high_risk_categories,json=highRiskCategories,proto3" json:"high_risk_categories,omitempty"`
	AllowedActions             []SanctionAction `protobuf:"varint,11,rep,packed,name=allowed_actions,json=allowedActions,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"allowed_actions,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e8e86b61a60d67, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWatchThreshold() uint32 {
	if m != nil {
		return m.WatchThreshold
	}
	return 0
}

func (m *Params) GetBlockThreshold() uint32 {
	if m != nil {
		return m.BlockThreshold
	}
	return 0
}

func (m *Params) GetFreezeThreshold() uint32 {
	if m != nil {
		return m.FreezeThreshold
	}
	return 0
}

func (m *Params) GetRevertThreshold() uint32 {
	if m != nil {
		return m.RevertThreshold
	}
	return 0
}

func (m *Params) GetQuorumThreshold() uint32 {
	if m != nil {
		return m.QuorumThreshold
	}
	return 0
}

func (m *Params) GetUnanimousRequiredForRevert() bool {
	if m != nil {
		return m.UnanimousRequiredForRevert
	}
	return false
}

func (m *Params) GetEvidenceTtlBlocks() uint64 {
	if m != nil {
		return m.EvidenceTtlBlocks
	}
	return 0
}

func (m *Params) GetVotingPeriodBlocks() uint64 {
	if m != nil {
		return m.VotingPeriodBlocks
	}
	return 0
}

func (m *Params) GetAcceptedRiskSources() []string {
	if m != nil {
		return m.AcceptedRiskSources
	}
	return nil
}

func (m *Params) GetHighRiskCategories() []string {
	if m != nil {
		return m.HighRiskCategories
	}
	return nil
}

func (m *Params) GetAllowedActions() []SanctionAction {
	if m != nil {
		return m.AllowedActions
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "crossrefd.sanction.v1.Params")
}

func init() {
	proto.RegisterFile("crossrefd/sanction/v1/params.proto", fileDescriptor_f7e8e86b61a60d67)
}

var fileDescriptor_f7e8e86b61a60d67 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0x06, 0xe0, 0x98, 0x84, 0xd0, 0x0e, 0x22, 0x01, 0x97, 0x4a, 0x56, 0x25, 0x2c, 0x53, 0x09,
	0x61, 0x36, 0x36, 0x2d, 0x27, 0x68, 0x91, 0x10, 0x2b, 0x54, 0x4d, 0xbb, 0x62, 0x33, 0x9a, 0x8c,
	0x5f, 0xe2, 0x51, 0x1c, 0x8f, 0xfb, 0x66, 0xec, 0x02, 0xa7, 0xe0, 0x34, 0x9c, 0x81, 0x65, 0x97,
	0x2c, 0x51, 0x72, 0x91, 0x2a, 0x33, 0x76, 0x92, 0x4a, 0xd9, 0x44, 0xf1, 0xfb, 0xbf, 0xff, 0x59,
	0x96, 0x1e, 0x39, 0x15, 0xa8, 0xb4, 0x46, 0x98, 0x66, 0xa9, 0xe6, 0xa5, 0x30, 0x52, 0x95, 0x69,
	0x73, 0x96, 0x56, 0x1c, 0xf9, 0x42, 0x27, 0x15, 0x2a, 0xa3, 0xfc, 0xe3, 0x8d, 0x49, 0x3a, 0x93,
	0x34, 0x67, 0x27, 0x6f, 0xf7, 0x57, 0xcd, 0xcf, 0x0a, 0xda, 0xe6, 0xe9, 0x9f, 0x01, 0x19, 0x5e,
	0xd9, 0x55, 0xfe, 0x7b, 0x32, 0xbe, 0xe3, 0x46, 0xe4, 0xcc, 0xe4, 0x08, 0x3a, 0x57, 0x45, 0x16,
	0x78, 0x91, 0x17, 0xbf, 0xa0, 0x23, 0x3b, 0xbe, 0xe9, 0xa6, 0x6b, 0x38, 0x29, 0x94, 0x98, 0xef,
	0xc0, 0x27, 0x0e, 0xda, 0xf1, 0x16, 0x7e, 0x20, 0x2f, 0xa7, 0x08, 0xf0, 0x0b, 0x76, 0x64, 0xdf,
	0xca, 0xb1, 0x9b, 0x3f, 0xa2, 0x08, 0x0d, 0xa0, 0xd9, 0xa1, 0x03, 0x47, 0xdd, 0xfc, 0x11, 0xbd,
	0xad, 0x15, 0xd6, 0x8b, 0x1d, 0xfa, 0xd4, 0x51, 0x37, 0xdf, 0xd2, 0x0b, 0xf2, 0xa6, 0x2e, 0x79,
	0x29, 0x17, 0xaa, 0xd6, 0x0c, 0xe1, 0xb6, 0x96, 0x08, 0x19, 0x9b, 0x2a, 0x64, 0x6e, 0x69, 0x30,
	0x8c, 0xbc, 0xf8, 0x80, 0x9e, 0x6c, 0x10, 0x6d, 0xcd, 0x17, 0x85, 0xd4, 0x0a, 0x3f, 0x21, 0x47,
	0xd0, 0xc8, 0x0c, 0x4a, 0x01, 0xcc, 0x98, 0x82, 0xd9, 0x4f, 0xd4, 0xc1, 0xb3, 0xc8, 0x8b, 0x07,
	0xf4, 0x55, 0x17, 0xdd, 0x98, 0xe2, 0xd2, 0x06, 0xfe, 0x47, 0xf2, 0xba, 0x51, 0x46, 0x96, 0x33,
	0x56, 0x01, 0x4a, 0x95, 0x75, 0x85, 0x03, 0x5b, 0xf0, 0x5d, 0x76, 0x65, 0xa3, 0xb6, 0x71, 0x4e,
	0x8e, 0xb9, 0x10, 0x50, 0x19, 0xc8, 0x18, 0x4a, 0x3d, 0x67, 0x5a, 0xd5, 0x28, 0x40, 0x07, 0x87,
	0x51, 0x3f, 0x3e, 0xa4, 0x47, 0x5d, 0x48, 0xa5, 0x9e, 0x5f, 0xbb, 0x68, 0xfd, 0x96, 0x5c, 0xce,
	0x72, 0xe7, 0x05, 0x37, 0x30, 0x53, 0x28, 0x41, 0x07, 0xc4, 0x56, 0xfc, 0x75, 0xb6, 0xe6, 0x9f,
	0x37, 0x89, 0xff, 0x8d, 0x8c, 0x79, 0x51, 0xa8, 0x3b, 0xc8, 0x18, 0xb7, 0x97, 0xa0, 0x83, 0xe7,
	0x51, 0x3f, 0x1e, 0x9d, 0xbf, 0x4b, 0xf6, 0x1e, 0x4f, 0x72, 0xdd, 0xfe, 0xbf, 0xb0, 0xbf, 0x74,
	0xd4, 0xb6, 0xdd, 0xa3, 0xbe, 0xfc, 0xfa, 0x77, 0x19, 0x7a, 0xf7, 0xcb, 0xd0, 0xfb, 0xbf, 0x0c,
	0xbd, 0xdf, 0xab, 0xb0, 0x77, 0xbf, 0x0a, 0x7b, 0xff, 0x56, 0x61, 0xef, 0x7b, 0x32, 0x93, 0x26,
	0xaf, 0x27, 0x89, 0x50, 0x8b, 0xb4, 0x5b, 0x9d, 0x6e, 0x2f, 0xf1, 0xc7, 0xf6, 0x16, 0xed, 0x21,
	0x4e, 0x86, 0xf6, 0x12, 0x3f, 0x3d, 0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0xbe, 0xd6, 0x7a, 0xe9,
	0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllowedActions) > 0 {
		dAtA2 := make([]byte, len(m.AllowedActions)*10)
		var j1 int
		for _, num := range m.AllowedActions {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.HighRiskCategories) > 0 {
		for iNdEx := len(m.HighRiskCategories) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HighRiskCategories[iNdEx])
			copy(dAtA[i:], m.HighRiskCategories[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.HighRiskCategories[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.AcceptedRiskSources) > 0 {
		for iNdEx := len(m.AcceptedRiskSources) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AcceptedRiskSources[iNdEx])
			copy(dAtA[i:], m.AcceptedRiskSources[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.AcceptedRiskSources[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.VotingPeriodBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VotingPeriodBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.EvidenceTtlBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EvidenceTtlBlocks))
		i--
		dAtA[i] = 0x38
	}
	if m.UnanimousRequiredForRevert {
		i--
		if m.UnanimousRequiredForRevert {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.QuorumThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.QuorumThreshold))
		i--
		dAtA[i] = 0x28
	}
	if m.RevertThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RevertThreshold))
		i--
		dAtA[i] = 0x20
	}
	if m.FreezeThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FreezeThreshold))
		i--
		dAtA[i] = 0x18
	}
	if m.BlockThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlockThreshold))
		i--
		dAtA[i] = 0x10
	}
	if m.WatchThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WatchThreshold))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.WatchThreshold != 0 {
		n += 1 + sovParams(uint64(m.WatchThreshold))
	}
	if m.BlockThreshold != 0 {
		n += 1 + sovParams(uint64(m.BlockThreshold))
	}
	if m.FreezeThreshold != 0 {
		n += 1 + sovParams(uint64(m.FreezeThreshold))
	}
	if m.RevertThreshold != 0 {
		n += 1 + sovParams(uint64(m.RevertThreshold))
	}
	if m.QuorumThreshold != 0 {
		n += 1 + sovParams(uint64(m.QuorumThreshold))
	}
	if m.UnanimousRequiredForRevert {
		n += 2
	}
	if m.EvidenceTtlBlocks != 0 {
		n += 1 + sovParams(uint64(m.EvidenceTtlBlocks))
	}
	if m.VotingPeriodBlocks != 0 {
		n += 1 + sovParams(uint64(m.VotingPeriodBlocks))
	}
	if len(m.AcceptedRiskSources) > 0 {
		for _, s := range m.AcceptedRiskSources {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.HighRiskCategories) > 0 {
		for _, s := range m.HighRiskCategories {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.AllowedActions) > 0 {
		l = 0
		for _, e := range m.AllowedActions {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WatchThreshold", wireType)
			}
			m.WatchThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WatchThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockThreshold", wireType)
			}
			m.BlockThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeThreshold", wireType)
			}
			m.FreezeThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FreezeThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevertThreshold", wireType)
			}
			m.RevertThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevertThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumThreshold", wireType)
			}
			m.QuorumThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QuorumThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnanimousRequiredForRevert", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UnanimousRequiredForRevert = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceTtlBlocks", wireType)
			}
			m.EvidenceTtlBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceTtlBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPeriodBlocks", wireType)
			}
			m.VotingPeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPeriodBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedRiskSources", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AcceptedRiskSources = append(m.AcceptedRiskSources, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighRiskCategories", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HighRiskCategories = append(m.HighRiskCategories, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 11:
			if wireType == 0 {
				var v SanctionAction
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= SanctionAction(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.AllowedActions = append(m.AllowedActions, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.AllowedActions) == 0 {
					m.AllowedActions = make([]SanctionAction, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v SanctionAction
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= SanctionAction(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.AllowedActions = append(m.AllowedActions, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedActions", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
