// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crossrefd/sanction/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterAgent struct {
	Authority string    `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Agent     AgentInfo `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent"`
}

func (m *MsgRegisterAgent) Reset()         { *m = MsgRegisterAgent{} }
func (m *MsgRegisterAgent) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAgent) ProtoMessage()    {}
func (*MsgRegisterAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{0}
}
func (m *MsgRegisterAgent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAgent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAgent.Merge(m, src)
}
func (m *MsgRegisterAgent) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAgent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAgent proto.InternalMessageInfo

func (m *MsgRegisterAgent) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRegisterAgent) GetAgent() AgentInfo {
	if m != nil {
		return m.Agent
	}
	return AgentInfo{}
}

type MsgRegisterAgentResponse struct {
}

func (m *MsgRegisterAgentResponse) Reset()         { *m = MsgRegisterAgentResponse{} }
func (m *MsgRegisterAgentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterAgentResponse) ProtoMessage()    {}
func (*MsgRegisterAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{1}
}
func (m *MsgRegisterAgentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterAgentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterAgentResponse.Merge(m, src)
}
func (m *MsgRegisterAgentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterAgentResponse proto.InternalMessageInfo

type MsgSubmitRiskReport struct {
	Submitter string     `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Report    RiskReport `protobuf:"bytes,2,opt,name=report,proto3" json:"report"`
}

func (m *MsgSubmitRiskReport) Reset()         { *m = MsgSubmitRiskReport{} }
func (m *MsgSubmitRiskReport) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRiskReport) ProtoMessage()    {}
func (*MsgSubmitRiskReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{2}
}
func (m *MsgSubmitRiskReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRiskReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRiskReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRiskReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRiskReport.Merge(m, src)
}
func (m *MsgSubmitRiskReport) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRiskReport) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRiskReport.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRiskReport proto.InternalMessageInfo

func (m *MsgSubmitRiskReport) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitRiskReport) GetReport() RiskReport {
	if m != nil {
		return m.Report
	}
	return RiskReport{}
}

type MsgSubmitRiskReportResponse struct {
	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (m *MsgSubmitRiskReportResponse) Reset()         { *m = MsgSubmitRiskReportResponse{} }
func (m *MsgSubmitRiskReportResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitRiskReportResponse) ProtoMessage()    {}
func (*MsgSubmitRiskReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{3}
}
func (m *MsgSubmitRiskReportResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitRiskReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitRiskReportResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitRiskReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitRiskReportResponse.Merge(m, src)
}
func (m *MsgSubmitRiskReportResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitRiskReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitRiskReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitRiskReportResponse proto.InternalMessageInfo

func (m *MsgSubmitRiskReportResponse) GetReportId() string {
	if m != nil {
		return m.ReportId
	}
	return ""
}

type MsgOpenSanctionCase struct {
	Submitter       string             `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	CaseId          string             `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash          []byte             `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string             `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetType      SanctionTargetType `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=crossrefd.sanction.v1.SanctionTargetType" json:"target_type,omitempty"`
	RequestedAction SanctionAction     `protobuf:"varint,6,opt,name=requested_action,json=requestedAction,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"requested_action,omitempty"`
	ReportIds       []string           `protobuf:"bytes,7,rep,name=report_ids,json=reportIds,proto3" json:"report_ids,omitempty"`
	PolicyVersion   string             `protobuf:"bytes,8,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
}

func (m *MsgOpenSanctionCase) Reset()         { *m = MsgOpenSanctionCase{} }
func (m *MsgOpenSanctionCase) String() string { return proto.CompactTextString(m) }
func (*MsgOpenSanctionCase) ProtoMessage()    {}
func (*MsgOpenSanctionCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{4}
}
func (m *MsgOpenSanctionCase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenSanctionCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenSanctionCase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenSanctionCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenSanctionCase.Merge(m, src)
}
func (m *MsgOpenSanctionCase) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenSanctionCase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenSanctionCase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenSanctionCase proto.InternalMessageInfo

func (m *MsgOpenSanctionCase) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgOpenSanctionCase) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *MsgOpenSanctionCase) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *MsgOpenSanctionCase) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *MsgOpenSanctionCase) GetTargetType() SanctionTargetType {
	if m != nil {
		return m.TargetType
	}
	return SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED
}

func (m *MsgOpenSanctionCase) GetRequestedAction() SanctionAction {
	if m != nil {
		return m.RequestedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (m *MsgOpenSanctionCase) GetReportIds() []string {
	if m != nil {
		return m.ReportIds
	}
	return nil
}

func (m *MsgOpenSanctionCase) GetPolicyVersion() string {
	if m != nil {
		return m.PolicyVersion
	}
	return ""
}

type MsgOpenSanctionCaseResponse struct {
	CaseId string `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
}

func (m *MsgOpenSanctionCaseResponse) Reset()         { *m = MsgOpenSanctionCaseResponse{} }
func (m *MsgOpenSanctionCaseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgOpenSanctionCaseResponse) ProtoMessage()    {}
func (*MsgOpenSanctionCaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{5}
}
func (m *MsgOpenSanctionCaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgOpenSanctionCaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgOpenSanctionCaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgOpenSanctionCaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgOpenSanctionCaseResponse.Merge(m, src)
}
func (m *MsgOpenSanctionCaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgOpenSanctionCaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgOpenSanctionCaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgOpenSanctionCaseResponse proto.InternalMessageInfo

func (m *MsgOpenSanctionCaseResponse) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

type MsgSubmitSanctionVote struct {
	Submitter string       `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Vote      SanctionVote `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote"`
}

func (m *MsgSubmitSanctionVote) Reset()         { *m = MsgSubmitSanctionVote{} }
func (m *MsgSubmitSanctionVote) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSanctionVote) ProtoMessage()    {}
func (*MsgSubmitSanctionVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{6}
}
func (m *MsgSubmitSanctionVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSanctionVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSanctionVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSanctionVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSanctionVote.Merge(m, src)
}
func (m *MsgSubmitSanctionVote) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSanctionVote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSanctionVote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSanctionVote proto.InternalMessageInfo

func (m *MsgSubmitSanctionVote) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitSanctionVote) GetVote() SanctionVote {
	if m != nil {
		return m.Vote
	}
	return SanctionVote{}
}

type MsgSubmitSanctionVoteResponse struct {
	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Rejected bool `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
}

func (m *MsgSubmitSanctionVoteResponse) Reset()         { *m = MsgSubmitSanctionVoteResponse{} }
func (m *MsgSubmitSanctionVoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSanctionVoteResponse) ProtoMessage()    {}
func (*MsgSubmitSanctionVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{7}
}
func (m *MsgSubmitSanctionVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSanctionVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSanctionVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSanctionVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSanctionVoteResponse.Merge(m, src)
}
func (m *MsgSubmitSanctionVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSanctionVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSanctionVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSanctionVoteResponse proto.InternalMessageInfo

func (m *MsgSubmitSanctionVoteResponse) GetApproved() bool {
	if m != nil {
		return m.Approved
	}
	return false
}

func (m *MsgSubmitSanctionVoteResponse) GetRejected() bool {
	if m != nil {
		return m.Rejected
	}
	return false
}

type MsgExecuteSanction struct {
	Executor      string `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	CaseId        string `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	ResultMessage string `protobuf:"bytes,3,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
}

func (m *MsgExecuteSanction) Reset()         { *m = MsgExecuteSanction{} }
func (m *MsgExecuteSanction) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteSanction) ProtoMessage()    {}
func (*MsgExecuteSanction) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{8}
}
func (m *MsgExecuteSanction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteSanction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteSanction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteSanction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteSanction.Merge(m, src)
}
func (m *MsgExecuteSanction) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteSanction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteSanction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteSanction proto.InternalMessageInfo

func (m *MsgExecuteSanction) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *MsgExecuteSanction) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *MsgExecuteSanction) GetResultMessage() string {
	if m != nil {
		return m.ResultMessage
	}
	return ""
}

type MsgExecuteSanctionResponse struct {
	Record ExecutionRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record"`
}

func (m *MsgExecuteSanctionResponse) Reset()         { *m = MsgExecuteSanctionResponse{} }
func (m *MsgExecuteSanctionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExecuteSanctionResponse) ProtoMessage()    {}
func (*MsgExecuteSanctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{9}
}
func (m *MsgExecuteSanctionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExecuteSanctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExecuteSanctionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExecuteSanctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExecuteSanctionResponse.Merge(m, src)
}
func (m *MsgExecuteSanctionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExecuteSanctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExecuteSanctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExecuteSanctionResponse proto.InternalMessageInfo

func (m *MsgExecuteSanctionResponse) GetRecord() ExecutionRecord {
	if m != nil {
		return m.Record
	}
	return ExecutionRecord{}
}

type MsgRevokeSanction struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	CaseId    string `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Reason    string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgRevokeSanction) Reset()         { *m = MsgRevokeSanction{} }
func (m *MsgRevokeSanction) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeSanction) ProtoMessage()    {}
func (*MsgRevokeSanction) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{10}
}
func (m *MsgRevokeSanction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeSanction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeSanction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeSanction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeSanction.Merge(m, src)
}
func (m *MsgRevokeSanction) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeSanction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeSanction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeSanction proto.InternalMessageInfo

func (m *MsgRevokeSanction) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRevokeSanction) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *MsgRevokeSanction) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type MsgRevokeSanctionResponse struct {
}

func (m *MsgRevokeSanctionResponse) Reset()         { *m = MsgRevokeSanctionResponse{} }
func (m *MsgRevokeSanctionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeSanctionResponse) ProtoMessage()    {}
func (*MsgRevokeSanctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{11}
}
func (m *MsgRevokeSanctionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeSanctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeSanctionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeSanctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeSanctionResponse.Merge(m, src)
}
func (m *MsgRevokeSanctionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeSanctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeSanctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeSanctionResponse proto.InternalMessageInfo

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{12}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16e8c186fccbdede, []int{13}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterAgent)(nil), "crossrefd.sanction.v1.MsgRegisterAgent")
	proto.RegisterType((*MsgRegisterAgentResponse)(nil), "crossrefd.sanction.v1.MsgRegisterAgentResponse")
	proto.RegisterType((*MsgSubmitRiskReport)(nil), "crossrefd.sanction.v1.MsgSubmitRiskReport")
	proto.RegisterType((*MsgSubmitRiskReportResponse)(nil), "crossrefd.sanction.v1.MsgSubmitRiskReportResponse")
	proto.RegisterType((*MsgOpenSanctionCase)(nil), "crossrefd.sanction.v1.MsgOpenSanctionCase")
	proto.RegisterType((*MsgOpenSanctionCaseResponse)(nil), "crossrefd.sanction.v1.MsgOpenSanctionCaseResponse")
	proto.RegisterType((*MsgSubmitSanctionVote)(nil), "crossrefd.sanction.v1.MsgSubmitSanctionVote")
	proto.RegisterType((*MsgSubmitSanctionVoteResponse)(nil), "crossrefd.sanction.v1.MsgSubmitSanctionVoteResponse")
	proto.RegisterType((*MsgExecuteSanction)(nil), "crossrefd.sanction.v1.MsgExecuteSanction")
	proto.RegisterType((*MsgExecuteSanctionResponse)(nil), "crossrefd.sanction.v1.MsgExecuteSanctionResponse")
	proto.RegisterType((*MsgRevokeSanction)(nil), "crossrefd.sanction.v1.MsgRevokeSanction")
	proto.RegisterType((*MsgRevokeSanctionResponse)(nil), "crossrefd.sanction.v1.MsgRevokeSanctionResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "crossrefd.sanction.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "crossrefd.sanction.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("crossrefd/sanction/v1/tx.proto", fileDescriptor_16e8c186fccbdede) }

var fileDescriptor_16e8c186fccbdede = []byte{
	// 1015 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0x36, 0x89, 0x6b, 0xbf, 0x34, 0x4e, 0xba, 0xb4, 0xc4, 0xd9, 0x28, 0xc6, 0x5d, 0x48,
	0xea, 0x5a, 0x60, 0x13, 0x53, 0x15, 0x30, 0x54, 0x25, 0x01, 0xa4, 0x06, 0xc9, 0xa2, 0xda, 0x94,
	0x22, 0x71, 0xb1, 0x36, 0xeb, 0xc9, 0x7a, 0x69, 0xbc, 0xb3, 0xcc, 0x8c, 0x2d, 0xe7, 0x86, 0x38,
	0x72, 0xe2, 0x27, 0x70, 0xe4, 0x98, 0x03, 0x12, 0x77, 0x04, 0x52, 0x25, 0x84, 0x54, 0x71, 0xe2,
	0x84, 0x20, 0x39, 0xe4, 0x6f, 0xa0, 0x99, 0xd9, 0x1d, 0x6f, 0xd6, 0xde, 0xd8, 0xc9, 0xc5, 0xf2,
	0xbc, 0xf9, 0xe6, 0xbd, 0xf7, 0x7d, 0xf3, 0xde, 0xbc, 0x85, 0xa2, 0x43, 0x30, 0xa5, 0x04, 0x1d,
	0xb4, 0x6b, 0xd4, 0xf6, 0x1d, 0xe6, 0x61, 0xbf, 0xd6, 0xdf, 0xaa, 0xb1, 0x41, 0x35, 0x20, 0x98,
	0x61, 0xfd, 0xb6, 0xda, 0xaf, 0x46, 0xfb, 0xd5, 0xfe, 0x96, 0xb1, 0xe2, 0x60, 0xda, 0xc5, 0xb4,
	0xd6, 0xa5, 0x2e, 0x87, 0x77, 0xa9, 0x2b, 0xf1, 0xc6, 0xaa, 0xdc, 0x68, 0x89, 0x55, 0x4d, 0x2e,
	0xc2, 0xad, 0x9b, 0x76, 0xd7, 0xf3, 0x71, 0x4d, 0xfc, 0x86, 0xa6, 0x5b, 0x2e, 0x76, 0xb1, 0x84,
	0xf2, 0x7f, 0xa1, 0xd5, 0x1c, 0x9f, 0x53, 0x60, 0x13, 0xbb, 0x1b, 0x39, 0xbb, 0x93, 0x92, 0xf7,
	0x51, 0x80, 0x42, 0x88, 0xf9, 0xab, 0x06, 0xcb, 0x4d, 0xea, 0x5a, 0xc8, 0xf5, 0x28, 0x43, 0x64,
	0xdb, 0x45, 0x3e, 0xd3, 0x1f, 0x40, 0xce, 0xee, 0xb1, 0x0e, 0x26, 0x1e, 0x3b, 0x2a, 0x68, 0x25,
	0xad, 0x9c, 0xdb, 0x29, 0xfc, 0xf5, 0xf3, 0x5b, 0xb7, 0xc2, 0x4c, 0xb7, 0xdb, 0x6d, 0x82, 0x28,
	0xdd, 0x63, 0xc4, 0xf3, 0x5d, 0x6b, 0x08, 0xd5, 0x3f, 0x84, 0x79, 0x9b, 0x3b, 0x28, 0x5c, 0x2b,
	0x69, 0xe5, 0x85, 0x7a, 0xa9, 0x3a, 0x56, 0x97, 0xaa, 0x08, 0xb2, 0xeb, 0x1f, 0xe0, 0x9d, 0xb9,
	0x17, 0xff, 0xbc, 0x36, 0x63, 0xc9, 0x43, 0x8d, 0xf7, 0xbe, 0x3b, 0x3b, 0xae, 0x0c, 0xbd, 0x7d,
	0x7f, 0x76, 0x5c, 0xd9, 0x18, 0x12, 0x18, 0x0c, 0x29, 0x24, 0xf3, 0x35, 0x0d, 0x28, 0x24, 0x6d,
	0x16, 0xa2, 0x01, 0xf6, 0x29, 0x32, 0xff, 0xd0, 0xe0, 0x95, 0x26, 0x75, 0xf7, 0x7a, 0xfb, 0x5d,
	0x8f, 0x59, 0x1e, 0x7d, 0x6e, 0xa1, 0x00, 0x13, 0xc1, 0x91, 0x0a, 0x1b, 0x43, 0x64, 0x32, 0x47,
	0x05, 0xd5, 0x1f, 0x41, 0x86, 0x08, 0x0f, 0x21, 0xc9, 0x3b, 0x29, 0x24, 0x87, 0xa1, 0x42, 0x96,
	0xe1, 0xb1, 0xc6, 0x07, 0x82, 0xa6, 0x72, 0xc8, 0x69, 0x96, 0xd3, 0x68, 0x26, 0xb3, 0x36, 0x1b,
	0xb0, 0x36, 0xc6, 0x1c, 0x91, 0xd5, 0xd7, 0x20, 0x27, 0xa3, 0xb4, 0xbc, 0xb6, 0x24, 0x65, 0x65,
	0xa5, 0x61, 0xb7, 0x6d, 0xfe, 0x37, 0x2b, 0x94, 0xf8, 0x3c, 0x40, 0xfe, 0x5e, 0x18, 0xe3, 0x63,
	0x9b, 0xa2, 0x2b, 0x2b, 0xb1, 0x02, 0xd7, 0x1d, 0x9b, 0x22, 0x1e, 0xea, 0x9a, 0x08, 0x95, 0xe1,
	0xcb, 0xdd, 0x36, 0xdf, 0x60, 0x83, 0x56, 0xc7, 0xa6, 0x9d, 0xc2, 0x6c, 0x49, 0x2b, 0xdf, 0xb0,
	0x32, 0x6c, 0xf0, 0xd8, 0xa6, 0x1d, 0xfd, 0x11, 0xe4, 0x99, 0x4d, 0x5c, 0xc4, 0x5a, 0xb6, 0x74,
	0x5a, 0x98, 0x9b, 0x10, 0x6e, 0x51, 0xe2, 0x43, 0xa3, 0xfe, 0x19, 0x2c, 0x84, 0x0e, 0x78, 0x0d,
	0x17, 0xe6, 0x4b, 0x5a, 0x39, 0x5f, 0xbf, 0x97, 0x72, 0x03, 0x11, 0xc9, 0xa7, 0xe2, 0xc4, 0xd3,
	0xa3, 0x00, 0x59, 0xc0, 0xd4, 0x7f, 0xfd, 0x09, 0x2c, 0x13, 0xf4, 0x4d, 0x0f, 0x51, 0x86, 0xda,
	0x2d, 0x5b, 0x20, 0x0b, 0x19, 0xe1, 0x70, 0x63, 0x82, 0xc3, 0x6d, 0xf1, 0x6b, 0x2d, 0xa9, 0xe3,
	0xd2, 0xa0, 0xaf, 0x03, 0x28, 0xf5, 0x69, 0xe1, 0x7a, 0x69, 0xb6, 0x9c, 0xb3, 0x72, 0x91, 0xfc,
	0x54, 0xdf, 0x80, 0x7c, 0x80, 0x0f, 0x3d, 0xe7, 0xa8, 0xd5, 0x47, 0x84, 0xf2, 0x70, 0x59, 0x21,
	0xdb, 0xa2, 0xb4, 0x3e, 0x93, 0xc6, 0x4b, 0xd5, 0x47, 0xf2, 0x2e, 0xcd, 0x07, 0xa2, 0x3e, 0x92,
	0x66, 0x55, 0x1f, 0xb1, 0x2b, 0xd3, 0xe2, 0x57, 0x66, 0xfe, 0xa9, 0xc1, 0x6d, 0x55, 0x58, 0xd1,
	0xd1, 0x67, 0x98, 0x5d, 0xbd, 0x3a, 0x1e, 0xc2, 0x5c, 0x1f, 0x33, 0x14, 0x76, 0xc9, 0xeb, 0x13,
	0x24, 0xe5, 0xa1, 0xc2, 0x3e, 0x11, 0xc7, 0x1a, 0x0f, 0x47, 0x55, 0xa8, 0x5c, 0xdc, 0x25, 0x71,
	0x57, 0xe6, 0x97, 0xb0, 0x3e, 0x76, 0x43, 0x29, 0x61, 0x40, 0xd6, 0x0e, 0x02, 0x82, 0xfb, 0x48,
	0x4a, 0x91, 0xb5, 0xd4, 0x9a, 0xef, 0x11, 0xf4, 0x35, 0x72, 0x18, 0x92, 0x95, 0x9d, 0xb5, 0xd4,
	0xda, 0xfc, 0x5d, 0x03, 0xbd, 0x49, 0xdd, 0x4f, 0x07, 0xc8, 0xe9, 0x31, 0x14, 0xb9, 0xd6, 0xef,
	0x43, 0x16, 0x09, 0x13, 0x9e, 0x2c, 0x92, 0x42, 0xa6, 0x77, 0xd0, 0x06, 0xe4, 0x09, 0xa2, 0xbd,
	0x43, 0xd6, 0xea, 0x22, 0x4a, 0x6d, 0x17, 0x89, 0x46, 0xca, 0x59, 0x8b, 0xd2, 0xda, 0x94, 0xc6,
	0xc6, 0xfb, 0x5c, 0x24, 0xe5, 0x8e, 0x6b, 0x74, 0x37, 0x4d, 0xa3, 0x44, 0xc2, 0xe6, 0x3e, 0x18,
	0xa3, 0x56, 0xa5, 0xce, 0x27, 0xfc, 0x91, 0x73, 0x30, 0x91, 0xda, 0x2c, 0xd4, 0x37, 0x53, 0xae,
	0x4f, 0x9e, 0x17, 0x27, 0x39, 0x7a, 0xf8, 0xd2, 0xf1, 0x95, 0xf9, 0x8b, 0x06, 0x37, 0xc5, 0xbb,
	0xdc, 0xc7, 0xcf, 0x87, 0x52, 0x5d, 0x75, 0xb8, 0xa4, 0x8a, 0xf5, 0x2a, 0x4f, 0xd6, 0xa6, 0xd8,
	0x0f, 0x45, 0x0a, 0x57, 0x52, 0x9d, 0xf3, 0xf3, 0x64, 0x33, 0x7d, 0x9e, 0xc4, 0x73, 0x34, 0xd7,
	0x60, 0x75, 0xc4, 0xa8, 0x26, 0xca, 0x6f, 0x1a, 0x2c, 0x35, 0xa9, 0xfb, 0x45, 0xd0, 0xb6, 0x19,
	0x7a, 0x22, 0xe6, 0xed, 0x95, 0x49, 0x7d, 0x04, 0x19, 0x39, 0xb1, 0xc3, 0x3e, 0x59, 0x4f, 0x11,
	0x5a, 0x86, 0xd9, 0xc9, 0x71, 0x7d, 0x7f, 0x3a, 0x3b, 0xae, 0x68, 0x56, 0x78, 0xae, 0xf1, 0xee,
	0x28, 0xcb, 0x37, 0xd2, 0x58, 0xc6, 0x53, 0x36, 0x57, 0x61, 0x25, 0x61, 0x8a, 0x18, 0xd6, 0x7f,
	0xcc, 0xc0, 0x6c, 0x93, 0xba, 0xba, 0x07, 0x8b, 0xe7, 0x3f, 0x0c, 0xee, 0xa6, 0xa4, 0x97, 0x9c,
	0xbe, 0x46, 0x6d, 0x4a, 0xa0, 0xaa, 0x38, 0x02, 0xcb, 0x23, 0x23, 0xba, 0x92, 0xee, 0x24, 0x89,
	0x35, 0xea, 0xd3, 0x63, 0xe3, 0x31, 0x47, 0x86, 0xe1, 0x05, 0x31, 0x93, 0xd8, 0x8b, 0x62, 0xa6,
	0xbe, 0xc0, 0x03, 0xd0, 0xc7, 0x3c, 0xb2, 0x6f, 0x4e, 0xca, 0x3e, 0x8e, 0x36, 0xee, 0x5f, 0x06,
	0xad, 0x22, 0x63, 0x58, 0x4a, 0xbe, 0x5a, 0xf7, 0xd2, 0x1d, 0x25, 0xa0, 0xc6, 0xd6, 0xd4, 0x50,
	0x15, 0xf0, 0x10, 0xf2, 0x89, 0xd6, 0x2f, 0x5f, 0x54, 0x15, 0x71, 0xa4, 0xf1, 0xf6, 0xb4, 0x48,
	0x15, 0xed, 0x00, 0x6e, 0x9c, 0xeb, 0xc8, 0xcd, 0x74, 0x0f, 0x71, 0x9c, 0x51, 0x9d, 0x0e, 0x17,
	0xc5, 0x31, 0xe6, 0xbf, 0xe5, 0xed, 0xb7, 0xf3, 0xf8, 0xc5, 0x49, 0x51, 0x7b, 0x79, 0x52, 0xd4,
	0xfe, 0x3d, 0x29, 0x6a, 0x3f, 0x9c, 0x16, 0x67, 0x5e, 0x9e, 0x16, 0x67, 0xfe, 0x3e, 0x2d, 0xce,
	0x7c, 0x55, 0x75, 0x3d, 0xd6, 0xe9, 0xed, 0x57, 0x1d, 0xdc, 0xad, 0x45, 0xae, 0x6b, 0x63, 0x3b,
	0x52, 0x7c, 0x87, 0xef, 0x67, 0xc4, 0x87, 0xf8, 0x3b, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4b,
	0xdc, 0x05, 0x1d, 0x65, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterAgent(ctx context.Context, in *MsgRegisterAgent, opts ...grpc.CallOption) (*MsgRegisterAgentResponse, error)
	SubmitRiskReport(ctx context.Context, in *MsgSubmitRiskReport, opts ...grpc.CallOption) (*MsgSubmitRiskReportResponse, error)
	OpenSanctionCase(ctx context.Context, in *MsgOpenSanctionCase, opts ...grpc.CallOption) (*MsgOpenSanctionCaseResponse, error)
	SubmitSanctionVote(ctx context.Context, in *MsgSubmitSanctionVote, opts ...grpc.CallOption) (*MsgSubmitSanctionVoteResponse, error)
	ExecuteSanction(ctx context.Context, in *MsgExecuteSanction, opts ...grpc.CallOption) (*MsgExecuteSanctionResponse, error)
	RevokeSanction(ctx context.Context, in *MsgRevokeSanction, opts ...grpc.CallOption) (*MsgRevokeSanctionResponse, error)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterAgent(ctx context.Context, in *MsgRegisterAgent, opts ...grpc.CallOption) (*MsgRegisterAgentResponse, error) {
	out := new(MsgRegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitRiskReport(ctx context.Context, in *MsgSubmitRiskReport, opts ...grpc.CallOption) (*MsgSubmitRiskReportResponse, error) {
	out := new(MsgSubmitRiskReportResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/SubmitRiskReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) OpenSanctionCase(ctx context.Context, in *MsgOpenSanctionCase, opts ...grpc.CallOption) (*MsgOpenSanctionCaseResponse, error) {
	out := new(MsgOpenSanctionCaseResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/OpenSanctionCase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitSanctionVote(ctx context.Context, in *MsgSubmitSanctionVote, opts ...grpc.CallOption) (*MsgSubmitSanctionVoteResponse, error) {
	out := new(MsgSubmitSanctionVoteResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/SubmitSanctionVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExecuteSanction(ctx context.Context, in *MsgExecuteSanction, opts ...grpc.CallOption) (*MsgExecuteSanctionResponse, error) {
	out := new(MsgExecuteSanctionResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/ExecuteSanction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeSanction(ctx context.Context, in *MsgRevokeSanction, opts ...grpc.CallOption) (*MsgRevokeSanctionResponse, error) {
	out := new(MsgRevokeSanctionResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/RevokeSanction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/crossrefd.sanction.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterAgent(context.Context, *MsgRegisterAgent) (*MsgRegisterAgentResponse, error)
	SubmitRiskReport(context.Context, *MsgSubmitRiskReport) (*MsgSubmitRiskReportResponse, error)
	OpenSanctionCase(context.Context, *MsgOpenSanctionCase) (*MsgOpenSanctionCaseResponse, error)
	SubmitSanctionVote(context.Context, *MsgSubmitSanctionVote) (*MsgSubmitSanctionVoteResponse, error)
	ExecuteSanction(context.Context, *MsgExecuteSanction) (*MsgExecuteSanctionResponse, error)
	RevokeSanction(context.Context, *MsgRevokeSanction) (*MsgRevokeSanctionResponse, error)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterAgent(ctx context.Context, req *MsgRegisterAgent) (*MsgRegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (*UnimplementedMsgServer) SubmitRiskReport(ctx context.Context, req *MsgSubmitRiskReport) (*MsgSubmitRiskReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRiskReport not implemented")
}
func (*UnimplementedMsgServer) OpenSanctionCase(ctx context.Context, req *MsgOpenSanctionCase) (*MsgOpenSanctionCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenSanctionCase not implemented")
}
func (*UnimplementedMsgServer) SubmitSanctionVote(ctx context.Context, req *MsgSubmitSanctionVote) (*MsgSubmitSanctionVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSanctionVote not implemented")
}
func (*UnimplementedMsgServer) ExecuteSanction(ctx context.Context, req *MsgExecuteSanction) (*MsgExecuteSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSanction not implemented")
}
func (*UnimplementedMsgServer) RevokeSanction(ctx context.Context, req *MsgRevokeSanction) (*MsgRevokeSanctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSanction not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterAgent(ctx, req.(*MsgRegisterAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitRiskReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitRiskReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitRiskReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/SubmitRiskReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitRiskReport(ctx, req.(*MsgSubmitRiskReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_OpenSanctionCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgOpenSanctionCase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).OpenSanctionCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/OpenSanctionCase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).OpenSanctionCase(ctx, req.(*MsgOpenSanctionCase))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitSanctionVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitSanctionVote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitSanctionVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/SubmitSanctionVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitSanctionVote(ctx, req.(*MsgSubmitSanctionVote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExecuteSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteSanction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/ExecuteSanction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteSanction(ctx, req.(*MsgExecuteSanction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeSanction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeSanction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeSanction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/RevokeSanction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeSanction(ctx, req.(*MsgRevokeSanction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crossrefd.sanction.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crossrefd.sanction.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _Msg_RegisterAgent_Handler,
		},
		{
			MethodName: "SubmitRiskReport",
			Handler:    _Msg_SubmitRiskReport_Handler,
		},
		{
			MethodName: "OpenSanctionCase",
			Handler:    _Msg_OpenSanctionCase_Handler,
		},
		{
			MethodName: "SubmitSanctionVote",
			Handler:    _Msg_SubmitSanctionVote_Handler,
		},
		{
			MethodName: "ExecuteSanction",
			Handler:    _Msg_ExecuteSanction_Handler,
		},
		{
			MethodName: "RevokeSanction",
			Handler:    _Msg_RevokeSanction_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crossrefd/sanction/v1/tx.proto",
}

func (m *MsgRegisterAgent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAgent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAgent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Agent.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterAgentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterAgentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterAgentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRiskReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRiskReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRiskReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Report.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitRiskReportResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitRiskReportResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitRiskReportResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReportId) > 0 {
		i -= len(m.ReportId)
		copy(dAtA[i:], m.ReportId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReportId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgOpenSanctionCase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenSanctionCase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenSanctionCase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PolicyVersion) > 0 {
		i -= len(m.PolicyVersion)
		copy(dAtA[i:], m.PolicyVersion)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PolicyVersion)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ReportIds) > 0 {
		for iNdEx := len(m.ReportIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReportIds[iNdEx])
			copy(dAtA[i:], m.ReportIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.ReportIds[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.RequestedAction != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestedAction))
		i--
		dAtA[i] = 0x30
	}
	if m.TargetType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TargetType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.TargetAddress) > 0 {
		i -= len(m.TargetAddress)
		copy(dAtA[i:], m.TargetAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TargetAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgOpenSanctionCaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgOpenSanctionCaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgOpenSanctionCaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSanctionVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSanctionVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSanctionVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Vote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSanctionVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSanctionVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSanctionVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rejected {
		i--
		if m.Rejected {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Approved {
		i--
		if m.Approved {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteSanction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteSanction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteSanction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResultMessage) > 0 {
		i -= len(m.ResultMessage)
		copy(dAtA[i:], m.ResultMessage)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ResultMessage)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Executor) > 0 {
		i -= len(m.Executor)
		copy(dAtA[i:], m.Executor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Executor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExecuteSanctionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExecuteSanctionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExecuteSanctionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgRevokeSanction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeSanction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeSanction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeSanctionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeSanctionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeSanctionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterAgent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Agent.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterAgentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitRiskReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Report.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSubmitRiskReportResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReportId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgOpenSanctionCase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TargetAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TargetType != 0 {
		n += 1 + sovTx(uint64(m.TargetType))
	}
	if m.RequestedAction != 0 {
		n += 1 + sovTx(uint64(m.RequestedAction))
	}
	if len(m.ReportIds) > 0 {
		for _, s := range m.ReportIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.PolicyVersion)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgOpenSanctionCaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitSanctionVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Vote.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSubmitSanctionVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Approved {
		n += 2
	}
	if m.Rejected {
		n += 2
	}
	return n
}

func (m *MsgExecuteSanction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Executor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ResultMessage)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgExecuteSanctionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Record.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRevokeSanction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevokeSanctionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterAgent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAgent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAgent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Agent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterAgentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterAgentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterAgentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRiskReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRiskReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRiskReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Report.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitRiskReportResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitRiskReportResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitRiskReportResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgOpenSanctionCase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenSanctionCase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenSanctionCase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetType", wireType)
			}
			m.TargetType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetType |= SanctionTargetType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedAction", wireType)
			}
			m.RequestedAction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedAction |= SanctionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportIds = append(m.ReportIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgOpenSanctionCaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgOpenSanctionCaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgOpenSanctionCaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSanctionVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSanctionVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSanctionVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Vote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSanctionVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSanctionVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSanctionVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approved", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Approved = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rejected", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rejected = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteSanction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteSanction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteSanction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExecuteSanctionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExecuteSanctionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExecuteSanctionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeSanction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeSanction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeSanction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeSanctionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeSanctionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeSanctionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
