// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crossrefd/sanction/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SanctionTargetType int32

const (
	SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED SanctionTargetType = 0
	SanctionTargetType_SANCTION_TARGET_TYPE_TX          SanctionTargetType = 1
	SanctionTargetType_SANCTION_TARGET_TYPE_ADDRESS     SanctionTargetType = 2
)

var SanctionTargetType_name = map[int32]string{
	0: "SANCTION_TARGET_TYPE_UNSPECIFIED",
	1: "SANCTION_TARGET_TYPE_TX",
	2: "SANCTION_TARGET_TYPE_ADDRESS",
}

var SanctionTargetType_value = map[string]int32{
	"SANCTION_TARGET_TYPE_UNSPECIFIED": 0,
	"SANCTION_TARGET_TYPE_TX":          1,
	"SANCTION_TARGET_TYPE_ADDRESS":     2,
}

func (x SanctionTargetType) String() string {
	return proto.EnumName(SanctionTargetType_name, int32(x))
}

func (SanctionTargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{0}
}

type SanctionAction int32

const (
	SanctionAction_SANCTION_ACTION_UNSPECIFIED     SanctionAction = 0
	SanctionAction_SANCTION_ACTION_WATCH           SanctionAction = 1
	SanctionAction_SANCTION_ACTION_BLOCK_TX        SanctionAction = 2
	SanctionAction_SANCTION_ACTION_FREEZE_ADDRESS  SanctionAction = 3
	SanctionAction_SANCTION_ACTION_ESCROW_FUNDS    SanctionAction = 4
	SanctionAction_SANCTION_ACTION_REVERT_TRANSFER SanctionAction = 5
)

var SanctionAction_name = map[int32]string{
	0: "SANCTION_ACTION_UNSPECIFIED",
	1: "SANCTION_ACTION_WATCH",
	2: "SANCTION_ACTION_BLOCK_TX",
	3: "SANCTION_ACTION_FREEZE_ADDRESS",
	4: "SANCTION_ACTION_ESCROW_FUNDS",
	5: "SANCTION_ACTION_REVERT_TRANSFER",
}

var SanctionAction_value = map[string]int32{
	"SANCTION_ACTION_UNSPECIFIED":     0,
	"SANCTION_ACTION_WATCH":           1,
	"SANCTION_ACTION_BLOCK_TX":        2,
	"SANCTION_ACTION_FREEZE_ADDRESS":  3,
	"SANCTION_ACTION_ESCROW_FUNDS":    4,
	"SANCTION_ACTION_REVERT_TRANSFER": 5,
}

func (x SanctionAction) String() string {
	return proto.EnumName(SanctionAction_name, int32(x))
}

func (SanctionAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{1}
}

type CaseStatus int32

const (
	CaseStatus_CASE_STATUS_UNSPECIFIED CaseStatus = 0
	CaseStatus_CASE_STATUS_PENDING     CaseStatus = 1
	CaseStatus_CASE_STATUS_APPROVED    CaseStatus = 2
	CaseStatus_CASE_STATUS_REJECTED    CaseStatus = 3
	CaseStatus_CASE_STATUS_EXECUTED    CaseStatus = 4
	CaseStatus_CASE_STATUS_REVOKED     CaseStatus = 5
	CaseStatus_CASE_STATUS_EXPIRED     CaseStatus = 6
)

var CaseStatus_name = map[int32]string{
	0: "CASE_STATUS_UNSPECIFIED",
	1: "CASE_STATUS_PENDING",
	2: "CASE_STATUS_APPROVED",
	3: "CASE_STATUS_REJECTED",
	4: "CASE_STATUS_EXECUTED",
	5: "CASE_STATUS_REVOKED",
	6: "CASE_STATUS_EXPIRED",
}

var CaseStatus_value = map[string]int32{
	"CASE_STATUS_UNSPECIFIED": 0,
	"CASE_STATUS_PENDING":     1,
	"CASE_STATUS_APPROVED":    2,
	"CASE_STATUS_REJECTED":    3,
	"CASE_STATUS_EXECUTED":    4,
	"CASE_STATUS_REVOKED":     5,
	"CASE_STATUS_EXPIRED":     6,
}

func (x CaseStatus) String() string {
	return proto.EnumName(CaseStatus_name, int32(x))
}

func (CaseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{2}
}

type VoteOption int32

const (
	VoteOption_VOTE_OPTION_UNSPECIFIED VoteOption = 0
	VoteOption_VOTE_OPTION_APPROVE     VoteOption = 1
	VoteOption_VOTE_OPTION_REJECT      VoteOption = 2
	VoteOption_VOTE_OPTION_ABSTAIN     VoteOption = 3
)

var VoteOption_name = map[int32]string{
	0: "VOTE_OPTION_UNSPECIFIED",
	1: "VOTE_OPTION_APPROVE",
	2: "VOTE_OPTION_REJECT",
	3: "VOTE_OPTION_ABSTAIN",
}

var VoteOption_value = map[string]int32{
	"VOTE_OPTION_UNSPECIFIED": 0,
	"VOTE_OPTION_APPROVE":     1,
	"VOTE_OPTION_REJECT":      2,
	"VOTE_OPTION_ABSTAIN":     3,
}

func (x VoteOption) String() string {
	return proto.EnumName(VoteOption_name, int32(x))
}

func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{3}
}

type AgentInfo struct {
	AgentId           string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ValidatorOperator string `protobuf:"bytes,2,opt,name=validator_operator,json=validatorOperator,proto3" json:"validator_operator,omitempty"`
	SignerAddress     string `protobuf:"bytes,3,opt,name=signer_address,json=signerAddress,proto3" json:"signer_address,omitempty"`
	PublicKey         []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	LlmEndpointHash   string `protobuf:"bytes,5,opt,name=llm_endpoint_hash,json=llmEndpointHash,proto3" json:"llm_endpoint_hash,omitempty"`
	Active            bool   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{0}
}
func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return m.Size()
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *AgentInfo) GetValidatorOperator() string {
	if m != nil {
		return m.ValidatorOperator
	}
	return ""
}

func (m *AgentInfo) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *AgentInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AgentInfo) GetLlmEndpointHash() string {
	if m != nil {
		return m.LlmEndpointHash
	}
	return ""
}

func (m *AgentInfo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type RiskReport struct {
	ReportId           string   `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	TxHash             []byte   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	FromAddress        string   `protobuf:"bytes,3,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress          string   `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount             string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom              string   `protobuf:"bytes,6,opt,name=denom,proto3" json:"denom,omitempty"`
	RiskScore          uint32   `protobuf:"varint,7,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Categories         []string `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"`
	Source             string   `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	ObservedHeight     uint64   `protobuf:"varint,10,opt,name=observed_height,json=observedHeight,proto3" json:"observed_height,omitempty"`
	ExpiryHeight       uint64   `protobuf:"varint,11,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	EvidenceHash       []byte   `protobuf:"bytes,12,opt,name=evidence_hash,json=evidenceHash,proto3" json:"evidence_hash,omitempty"`
	Submitter          string   `protobuf:"bytes,13,opt,name=submitter,proto3" json:"submitter,omitempty"`
	SubmitterSignature []byte   `protobuf:"bytes,14,opt,name=submitter_signature,json=submitterSignature,proto3" json:"submitter_signature,omitempty"`
}

func (m *RiskReport) Reset()         { *m = RiskReport{} }
func (m *RiskReport) String() string { return proto.CompactTextString(m) }
func (*RiskReport) ProtoMessage()    {}
func (*RiskReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{1}
}
func (m *RiskReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RiskReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RiskReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RiskReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RiskReport.Merge(m, src)
}
func (m *RiskReport) XXX_Size() int {
	return m.Size()
}
func (m *RiskReport) XXX_DiscardUnknown() {
	xxx_messageInfo_RiskReport.DiscardUnknown(m)
}

var xxx_messageInfo_RiskReport proto.InternalMessageInfo

func (m *RiskReport) GetReportId() string {
	if m != nil {
		return m.ReportId
	}
	return ""
}

func (m *RiskReport) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *RiskReport) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *RiskReport) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *RiskReport) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RiskReport) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *RiskReport) GetRiskScore() uint32 {
	if m != nil {
		return m.RiskScore
	}
	return 0
}

func (m *RiskReport) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *RiskReport) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RiskReport) GetObservedHeight() uint64 {
	if m != nil {
		return m.ObservedHeight
	}
	return 0
}

func (m *RiskReport) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *RiskReport) GetEvidenceHash() []byte {
	if m != nil {
		return m.EvidenceHash
	}
	return nil
}

func (m *RiskReport) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *RiskReport) GetSubmitterSignature() []byte {
	if m != nil {
		return m.SubmitterSignature
	}
	return nil
}

type SanctionCase struct {
	CaseId               string             `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash               []byte             `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress        string             `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetType           SanctionTargetType `protobuf:"varint,4,opt,name=target_type,json=targetType,proto3,enum=crossrefd.sanction.v1.SanctionTargetType" json:"target_type,omitempty"`
	RequestedAction      SanctionAction     `protobuf:"varint,5,opt,name=requested_action,json=requestedAction,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"requested_action,omitempty"`
	Status               CaseStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=crossrefd.sanction.v1.CaseStatus" json:"status,omitempty"`
	ReportIds            []string           `protobuf:"bytes,7,rep,name=report_ids,json=reportIds,proto3" json:"report_ids,omitempty"`
	OpenedHeight         uint64             `protobuf:"varint,8,opt,name=opened_height,json=openedHeight,proto3" json:"opened_height,omitempty"`
	VotingDeadlineHeight uint64             `protobuf:"varint,9,opt,name=voting_deadline_height,json=votingDeadlineHeight,proto3" json:"voting_deadline_height,omitempty"`
	ExecutedHeight       uint64             `protobuf:"varint,10,opt,name=executed_height,json=executedHeight,proto3" json:"executed_height,omitempty"`
	PolicyVersion        string             `protobuf:"bytes,11,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	DecisionHash         []byte             `protobuf:"bytes,12,opt,name=decision_hash,json=decisionHash,proto3" json:"decision_hash,omitempty"`
}

func (m *SanctionCase) Reset()         { *m = SanctionCase{} }
func (m *SanctionCase) String() string { return proto.CompactTextString(m) }
func (*SanctionCase) ProtoMessage()    {}
func (*SanctionCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{2}
}
func (m *SanctionCase) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SanctionCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SanctionCase.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SanctionCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SanctionCase.Merge(m, src)
}
func (m *SanctionCase) XXX_Size() int {
	return m.Size()
}
func (m *SanctionCase) XXX_DiscardUnknown() {
	xxx_messageInfo_SanctionCase.DiscardUnknown(m)
}

var xxx_messageInfo_SanctionCase proto.InternalMessageInfo

func (m *SanctionCase) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *SanctionCase) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *SanctionCase) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *SanctionCase) GetTargetType() SanctionTargetType {
	if m != nil {
		return m.TargetType
	}
	return SanctionTargetType_SANCTION_TARGET_TYPE_UNSPECIFIED
}

func (m *SanctionCase) GetRequestedAction() SanctionAction {
	if m != nil {
		return m.RequestedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (m *SanctionCase) GetStatus() CaseStatus {
	if m != nil {
		return m.Status
	}
	return CaseStatus_CASE_STATUS_UNSPECIFIED
}

func (m *SanctionCase) GetReportIds() []string {
	if m != nil {
		return m.ReportIds
	}
	return nil
}

func (m *SanctionCase) GetOpenedHeight() uint64 {
	if m != nil {
		return m.OpenedHeight
	}
	return 0
}

func (m *SanctionCase) GetVotingDeadlineHeight() uint64 {
	if m != nil {
		return m.VotingDeadlineHeight
	}
	return 0
}

func (m *SanctionCase) GetExecutedHeight() uint64 {
	if m != nil {
		return m.ExecutedHeight
	}
	return 0
}

func (m *SanctionCase) GetPolicyVersion() string {
	if m != nil {
		return m.PolicyVersion
	}
	return ""
}

func (m *SanctionCase) GetDecisionHash() []byte {
	if m != nil {
		return m.DecisionHash
	}
	return nil
}

type SanctionVote struct {
	CaseId         string         `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	AgentId        string         `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Option         VoteOption     `protobuf:"varint,3,opt,name=option,proto3,enum=crossrefd.sanction.v1.VoteOption" json:"option,omitempty"`
	ApprovedAction SanctionAction `protobuf:"varint,4,opt,name=approved_action,json=approvedAction,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"approved_action,omitempty"`
	ReasonCode     string         `protobuf:"bytes,5,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	RationaleHash  []byte         `protobuf:"bytes,6,opt,name=rationale_hash,json=rationaleHash,proto3" json:"rationale_hash,omitempty"`
	SignedHeight   uint64         `protobuf:"varint,7,opt,name=signed_height,json=signedHeight,proto3" json:"signed_height,omitempty"`
	Signature      []byte         `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SanctionVote) Reset()         { *m = SanctionVote{} }
func (m *SanctionVote) String() string { return proto.CompactTextString(m) }
func (*SanctionVote) ProtoMessage()    {}
func (*SanctionVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{3}
}
func (m *SanctionVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SanctionVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SanctionVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SanctionVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SanctionVote.Merge(m, src)
}
func (m *SanctionVote) XXX_Size() int {
	return m.Size()
}
func (m *SanctionVote) XXX_DiscardUnknown() {
	xxx_messageInfo_SanctionVote.DiscardUnknown(m)
}

var xxx_messageInfo_SanctionVote proto.InternalMessageInfo

func (m *SanctionVote) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *SanctionVote) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *SanctionVote) GetOption() VoteOption {
	if m != nil {
		return m.Option
	}
	return VoteOption_VOTE_OPTION_UNSPECIFIED
}

func (m *SanctionVote) GetApprovedAction() SanctionAction {
	if m != nil {
		return m.ApprovedAction
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (m *SanctionVote) GetReasonCode() string {
	if m != nil {
		return m.ReasonCode
	}
	return ""
}

func (m *SanctionVote) GetRationaleHash() []byte {
	if m != nil {
		return m.RationaleHash
	}
	return nil
}

func (m *SanctionVote) GetSignedHeight() uint64 {
	if m != nil {
		return m.SignedHeight
	}
	return 0
}

func (m *SanctionVote) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ActiveSanction struct {
	CaseId          string         `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TxHash          []byte         `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string         `protobuf:"bytes,3,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Action          SanctionAction `protobuf:"varint,4,opt,name=action,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"action,omitempty"`
	ActivatedHeight uint64         `protobuf:"varint,5,opt,name=activated_height,json=activatedHeight,proto3" json:"activated_height,omitempty"`
}

func (m *ActiveSanction) Reset()         { *m = ActiveSanction{} }
func (m *ActiveSanction) String() string { return proto.CompactTextString(m) }
func (*ActiveSanction) ProtoMessage()    {}
func (*ActiveSanction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{4}
}
func (m *ActiveSanction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveSanction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveSanction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveSanction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveSanction.Merge(m, src)
}
func (m *ActiveSanction) XXX_Size() int {
	return m.Size()
}
func (m *ActiveSanction) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveSanction.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveSanction proto.InternalMessageInfo

func (m *ActiveSanction) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *ActiveSanction) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *ActiveSanction) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *ActiveSanction) GetAction() SanctionAction {
	if m != nil {
		return m.Action
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (m *ActiveSanction) GetActivatedHeight() uint64 {
	if m != nil {
		return m.ActivatedHeight
	}
	return 0
}

type FreezeRecord struct {
	Address      string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CaseId       string `protobuf:"bytes,2,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	FrozenHeight uint64 `protobuf:"varint,3,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height,omitempty"`
	Reason       string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *FreezeRecord) Reset()         { *m = FreezeRecord{} }
func (m *FreezeRecord) String() string { return proto.CompactTextString(m) }
func (*FreezeRecord) ProtoMessage()    {}
func (*FreezeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{5}
}
func (m *FreezeRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FreezeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FreezeRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FreezeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreezeRecord.Merge(m, src)
}
func (m *FreezeRecord) XXX_Size() int {
	return m.Size()
}
func (m *FreezeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FreezeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FreezeRecord proto.InternalMessageInfo

func (m *FreezeRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FreezeRecord) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *FreezeRecord) GetFrozenHeight() uint64 {
	if m != nil {
		return m.FrozenHeight
	}
	return 0
}

func (m *FreezeRecord) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ExecutionRecord struct {
	CaseId          string         `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	Action          SanctionAction `protobuf:"varint,2,opt,name=action,proto3,enum=crossrefd.sanction.v1.SanctionAction" json:"action,omitempty"`
	TxHash          []byte         `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TargetAddress   string         `protobuf:"bytes,4,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	Executor        string         `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	ExecutedHeight  uint64         `protobuf:"varint,6,opt,name=executed_height,json=executedHeight,proto3" json:"executed_height,omitempty"`
	ResultCode      string         `protobuf:"bytes,7,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	ResultMessage   string         `protobuf:"bytes,8,opt,name=result_message,json=resultMessage,proto3" json:"result_message,omitempty"`
	StateChangeHash []byte         `protobuf:"bytes,9,opt,name=state_change_hash,json=stateChangeHash,proto3" json:"state_change_hash,omitempty"`
}

func (m *ExecutionRecord) Reset()         { *m = ExecutionRecord{} }
func (m *ExecutionRecord) String() string { return proto.CompactTextString(m) }
func (*ExecutionRecord) ProtoMessage()    {}
func (*ExecutionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b84bda3e35588627, []int{6}
}
func (m *ExecutionRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionRecord.Merge(m, src)
}
func (m *ExecutionRecord) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionRecord proto.InternalMessageInfo

func (m *ExecutionRecord) GetCaseId() string {
	if m != nil {
		return m.CaseId
	}
	return ""
}

func (m *ExecutionRecord) GetAction() SanctionAction {
	if m != nil {
		return m.Action
	}
	return SanctionAction_SANCTION_ACTION_UNSPECIFIED
}

func (m *ExecutionRecord) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *ExecutionRecord) GetTargetAddress() string {
	if m != nil {
		return m.TargetAddress
	}
	return ""
}

func (m *ExecutionRecord) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *ExecutionRecord) GetExecutedHeight() uint64 {
	if m != nil {
		return m.ExecutedHeight
	}
	return 0
}

func (m *ExecutionRecord) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *ExecutionRecord) GetResultMessage() string {
	if m != nil {
		return m.ResultMessage
	}
	return ""
}

func (m *ExecutionRecord) GetStateChangeHash() []byte {
	if m != nil {
		return m.StateChangeHash
	}
	return nil
}

func init() {
	proto.RegisterEnum("crossrefd.sanction.v1.SanctionTargetType", SanctionTargetType_name, SanctionTargetType_value)
	proto.RegisterEnum("crossrefd.sanction.v1.SanctionAction", SanctionAction_name, SanctionAction_value)
	proto.RegisterEnum("crossrefd.sanction.v1.CaseStatus", CaseStatus_name, CaseStatus_value)
	proto.RegisterEnum("crossrefd.sanction.v1.VoteOption", VoteOption_name, VoteOption_value)
	proto.RegisterType((*AgentInfo)(nil), "crossrefd.sanction.v1.AgentInfo")
	proto.RegisterType((*RiskReport)(nil), "crossrefd.sanction.v1.RiskReport")
	proto.RegisterType((*SanctionCase)(nil), "crossrefd.sanction.v1.SanctionCase")
	proto.RegisterType((*SanctionVote)(nil), "crossrefd.sanction.v1.SanctionVote")
	proto.RegisterType((*ActiveSanction)(nil), "crossrefd.sanction.v1.ActiveSanction")
	proto.RegisterType((*FreezeRecord)(nil), "crossrefd.sanction.v1.FreezeRecord")
	proto.RegisterType((*ExecutionRecord)(nil), "crossrefd.sanction.v1.ExecutionRecord")
}

func init() { proto.RegisterFile("crossrefd/sanction/v1/types.proto", fileDescriptor_b84bda3e35588627) }

var fileDescriptor_b84bda3e35588627 = []byte{
	// 1328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xc1, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x25, 0x59, 0x36, 0xc7, 0xb6, 0xc4, 0x6c, 0x12, 0x9b, 0xf9, 0x93, 0x5f, 0x51, 0xe4,
	0xdf, 0x88, 0x63, 0xe0, 0xb7, 0x91, 0xb4, 0x97, 0x1c, 0x7a, 0x60, 0x24, 0x3a, 0x56, 0xd2, 0x4a,
	0x02, 0x49, 0x3b, 0x69, 0x2e, 0x04, 0x4d, 0xae, 0x65, 0x22, 0x12, 0x57, 0xdd, 0x5d, 0x09, 0x76,
	0x0e, 0x7d, 0x86, 0xbe, 0x49, 0xdf, 0xa1, 0xa7, 0x02, 0xbd, 0x04, 0x28, 0x0a, 0xe4, 0xd6, 0xc2,
	0x79, 0x91, 0x62, 0x77, 0x49, 0x4a, 0x56, 0x9c, 0x04, 0x29, 0xd0, 0x8b, 0xc4, 0xfd, 0xe6, 0xdb,
	0xdd, 0x99, 0xf9, 0x66, 0x86, 0x84, 0x7b, 0x21, 0x25, 0x8c, 0x51, 0x7c, 0x12, 0xed, 0xb1, 0x20,
	0x09, 0x79, 0x4c, 0x92, 0xbd, 0xc9, 0xc3, 0x3d, 0x7e, 0x3e, 0xc2, 0x6c, 0x77, 0x44, 0x09, 0x27,
	0xe8, 0x66, 0x4e, 0xd9, 0xcd, 0x28, 0xbb, 0x93, 0x87, 0x8d, 0x3f, 0x35, 0xd0, 0xad, 0x3e, 0x4e,
	0x78, 0x3b, 0x39, 0x21, 0xe8, 0x16, 0x2c, 0x07, 0x62, 0xe1, 0xc7, 0x91, 0xa9, 0xd5, 0xb5, 0x6d,
	0xdd, 0x59, 0x92, 0xeb, 0x76, 0x84, 0xfe, 0x0f, 0x68, 0x12, 0x0c, 0xe2, 0x28, 0xe0, 0x84, 0xfa,
	0x64, 0x84, 0xa9, 0x78, 0x30, 0x0b, 0x92, 0x74, 0x2d, 0xb7, 0x74, 0x53, 0x03, 0xda, 0x82, 0x0a,
	0x8b, 0xfb, 0x09, 0xa6, 0x7e, 0x10, 0x45, 0x14, 0x33, 0x66, 0x16, 0x25, 0x75, 0x4d, 0xa1, 0x96,
	0x02, 0xd1, 0x7f, 0x01, 0x46, 0xe3, 0xe3, 0x41, 0x1c, 0xfa, 0xaf, 0xf1, 0xb9, 0x59, 0xaa, 0x6b,
	0xdb, 0xab, 0x8e, 0xae, 0x90, 0xe7, 0xf8, 0x1c, 0xed, 0xc0, 0xb5, 0xc1, 0x60, 0xe8, 0xe3, 0x24,
	0x1a, 0x91, 0x38, 0xe1, 0xfe, 0x69, 0xc0, 0x4e, 0xcd, 0x45, 0x79, 0x50, 0x75, 0x30, 0x18, 0xda,
	0x29, 0x7e, 0x10, 0xb0, 0x53, 0xb4, 0x0e, 0xe5, 0x20, 0xe4, 0xf1, 0x04, 0x9b, 0xe5, 0xba, 0xb6,
	0xbd, 0xec, 0xa4, 0xab, 0xc6, 0x6f, 0x45, 0x00, 0x27, 0x66, 0xaf, 0x1d, 0x3c, 0x22, 0x94, 0xa3,
	0xdb, 0xa0, 0x53, 0xf9, 0x34, 0x8d, 0x71, 0x59, 0x01, 0xed, 0x08, 0x6d, 0xc0, 0x12, 0x3f, 0x53,
	0xb7, 0x14, 0xa4, 0x2f, 0x65, 0x7e, 0x26, 0x0f, 0xbf, 0x07, 0xab, 0x27, 0x94, 0x0c, 0xe7, 0x82,
	0x59, 0x11, 0xd8, 0x4c, 0x28, 0x9c, 0xe4, 0x84, 0x92, 0x24, 0xe8, 0x9c, 0x64, 0x66, 0xe1, 0xde,
	0x90, 0x8c, 0x13, 0x9e, 0xfa, 0x9f, 0xae, 0xd0, 0x0d, 0x58, 0x8c, 0x70, 0x42, 0x86, 0xd2, 0x6b,
	0xdd, 0x51, 0x0b, 0x71, 0x18, 0x8d, 0xd9, 0x6b, 0x9f, 0x85, 0x84, 0x62, 0x73, 0xa9, 0xae, 0x6d,
	0xaf, 0x39, 0xba, 0x40, 0x5c, 0x01, 0xa0, 0x1a, 0x40, 0x18, 0x70, 0xdc, 0x27, 0x34, 0xc6, 0xcc,
	0x5c, 0xae, 0x17, 0xb7, 0x75, 0x67, 0x06, 0x11, 0x97, 0x31, 0x32, 0xa6, 0x21, 0x36, 0x75, 0x75,
	0x99, 0x5a, 0xa1, 0xfb, 0x50, 0x25, 0xc7, 0x0c, 0xd3, 0x09, 0x8e, 0xfc, 0x53, 0x1c, 0xf7, 0x4f,
	0xb9, 0x09, 0x75, 0x6d, 0xbb, 0xe4, 0x54, 0x32, 0xf8, 0x40, 0xa2, 0x68, 0x13, 0xd6, 0xf0, 0xd9,
	0x28, 0xa6, 0xe7, 0x19, 0x6d, 0x45, 0xd2, 0x56, 0x15, 0x38, 0x43, 0x9a, 0xc4, 0x11, 0x4e, 0x42,
	0xac, 0x72, 0xb6, 0x2a, 0x73, 0xb6, 0x9a, 0x81, 0x32, 0x73, 0x77, 0x40, 0x67, 0xe3, 0xe3, 0x61,
	0xcc, 0x39, 0xa6, 0xe6, 0x9a, 0xca, 0x4a, 0x0e, 0xa0, 0x3d, 0xb8, 0x9e, 0x2f, 0x7c, 0x51, 0x1a,
	0x01, 0x1f, 0x53, 0x6c, 0x56, 0xe4, 0x41, 0x28, 0x37, 0xb9, 0x99, 0xa5, 0xf1, 0x73, 0x09, 0x56,
	0xdd, 0xb4, 0x7e, 0x9b, 0x01, 0xc3, 0x42, 0xb2, 0x30, 0x60, 0x78, 0xaa, 0x66, 0x59, 0x2c, 0x3f,
	0xa5, 0xe5, 0x16, 0x54, 0x78, 0x40, 0xfb, 0x98, 0xcf, 0x97, 0xa6, 0x42, 0x33, 0xc1, 0x9e, 0xc1,
	0x4a, 0x4a, 0x13, 0x6d, 0x24, 0x05, 0xad, 0x3c, 0x7a, 0xb0, 0x7b, 0x65, 0x1b, 0xed, 0x66, 0x2e,
	0x79, 0x72, 0x87, 0x77, 0x3e, 0xc2, 0x0e, 0xf0, 0xfc, 0x19, 0xf5, 0xc0, 0xa0, 0xf8, 0x87, 0x31,
	0x66, 0x1c, 0x47, 0x7e, 0x20, 0x99, 0xb2, 0x0c, 0x2a, 0x8f, 0xb6, 0x3e, 0x73, 0xa0, 0x25, 0x7f,
	0x9d, 0x6a, 0xbe, 0x5d, 0x01, 0xe8, 0x31, 0x94, 0x19, 0x0f, 0xf8, 0x98, 0xc9, 0xba, 0xa9, 0x3c,
	0xba, 0xf7, 0x91, 0x73, 0x44, 0x8e, 0x5c, 0x49, 0x74, 0xd2, 0x0d, 0xb2, 0xb6, 0xb2, 0x0e, 0x60,
	0xe6, 0x92, 0x2c, 0x1e, 0x3d, 0x6b, 0x01, 0x26, 0x54, 0x25, 0x23, 0x9c, 0x4c, 0x2b, 0x64, 0x59,
	0x49, 0xaf, 0xc0, 0x54, 0xfa, 0xaf, 0x61, 0x7d, 0x42, 0x78, 0x9c, 0xf4, 0xfd, 0x08, 0x07, 0xd1,
	0x20, 0x4e, 0x70, 0xc6, 0xd6, 0x25, 0xfb, 0x86, 0xb2, 0xb6, 0x52, 0x63, 0xba, 0xeb, 0x3e, 0x54,
	0xf1, 0x19, 0x0e, 0xc7, 0xfc, 0x83, 0xf2, 0xcb, 0xe0, 0x94, 0xb8, 0x05, 0x95, 0x11, 0x19, 0xc4,
	0xe1, 0xb9, 0x3f, 0xc1, 0x94, 0x89, 0x6c, 0xad, 0x28, 0x89, 0x14, 0x7a, 0xa4, 0x40, 0xe1, 0x6a,
	0x84, 0xc3, 0x58, 0x3c, 0x5f, 0x2a, 0xc0, 0x0c, 0x14, 0x72, 0x37, 0xde, 0x15, 0xa6, 0x15, 0x73,
	0x44, 0xf8, 0x27, 0x2a, 0x66, 0x76, 0xfa, 0x15, 0x2e, 0x4f, 0xbf, 0xc7, 0x50, 0x26, 0x23, 0x29,
	0x5b, 0xf1, 0x93, 0xe9, 0x16, 0x17, 0x74, 0x25, 0xd1, 0x49, 0x37, 0xa0, 0x0e, 0x54, 0x83, 0xd1,
	0x88, 0x92, 0xc9, 0x54, 0xfa, 0xd2, 0x97, 0x48, 0x5f, 0xc9, 0x76, 0xa7, 0xca, 0xdf, 0x85, 0x15,
	0x8a, 0x03, 0x46, 0x12, 0x3f, 0x24, 0x11, 0x4e, 0xa7, 0x09, 0x28, 0xa8, 0x49, 0x22, 0x2c, 0x92,
	0x47, 0x03, 0x41, 0x0d, 0x06, 0x69, 0x5f, 0x96, 0x65, 0x5a, 0xd6, 0x72, 0x54, 0xb6, 0xc1, 0x26,
	0xa8, 0x59, 0x9c, 0x4b, 0xb1, 0xa4, 0x74, 0x56, 0x60, 0x2a, 0x84, 0xe8, 0xde, 0xbc, 0x2b, 0x97,
	0xd5, 0x78, 0xce, 0x81, 0xc6, 0xef, 0x1a, 0x54, 0x2c, 0x39, 0x65, 0x33, 0x9f, 0xff, 0xbd, 0x76,
	0xfc, 0x46, 0x8d, 0xf7, 0x2f, 0xcd, 0x5e, 0xba, 0x09, 0x3d, 0x00, 0x43, 0xbe, 0x0f, 0x82, 0x99,
	0xda, 0x5b, 0x94, 0x01, 0x57, 0x73, 0x5c, 0xc5, 0xdc, 0xf8, 0x11, 0x56, 0xf7, 0x29, 0xc6, 0x6f,
	0xb0, 0x83, 0x43, 0x42, 0x23, 0x64, 0xc2, 0x52, 0xe6, 0x59, 0xf6, 0x4e, 0x4c, 0x7d, 0x9a, 0x09,
	0xb6, 0x70, 0x29, 0xd8, 0x4d, 0x58, 0x3b, 0xa1, 0xe4, 0x0d, 0x4e, 0xb2, 0xab, 0x8a, 0x2a, 0xb7,
	0x0a, 0x4c, 0x73, 0xbb, 0x0e, 0x65, 0xa5, 0x5a, 0xfa, 0xb2, 0x48, 0x57, 0x8d, 0x8b, 0x02, 0x54,
	0x6d, 0xd9, 0x0f, 0x22, 0x00, 0xe5, 0xc3, 0x47, 0xd3, 0x3a, 0x4d, 0x4b, 0xe1, 0x9f, 0xa4, 0x65,
	0x46, 0x95, 0xe2, 0x67, 0x54, 0x29, 0x5d, 0xa5, 0xca, 0x7f, 0x60, 0x59, 0xb5, 0x2e, 0xa1, 0x69,
	0x25, 0xe6, 0xeb, 0xab, 0xba, 0xbd, 0x7c, 0x65, 0xb7, 0xcb, 0x8a, 0x66, 0xe3, 0x01, 0x57, 0x15,
	0xbd, 0x94, 0x55, 0xb4, 0x80, 0xf2, 0x8a, 0x56, 0x84, 0x21, 0x66, 0x2c, 0xe8, 0xab, 0x52, 0xd4,
	0x9d, 0x35, 0x85, 0x7e, 0xa7, 0x40, 0xf1, 0xb5, 0x20, 0x46, 0x1c, 0xf6, 0xc3, 0xd3, 0x20, 0xe9,
	0xa7, 0xb5, 0xaf, 0xcb, 0xb0, 0xaa, 0xd2, 0xd0, 0x94, 0xb8, 0x88, 0x6f, 0xe7, 0x1c, 0xd0, 0x87,
	0x33, 0x1b, 0xfd, 0x0f, 0xea, 0xae, 0xd5, 0x69, 0x7a, 0xed, 0x6e, 0xc7, 0xf7, 0x2c, 0xe7, 0xa9,
	0xed, 0xf9, 0xde, 0xf7, 0x3d, 0xdb, 0x3f, 0xec, 0xb8, 0x3d, 0xbb, 0xd9, 0xde, 0x6f, 0xdb, 0x2d,
	0x63, 0x01, 0xdd, 0x86, 0x8d, 0x2b, 0x59, 0xde, 0x4b, 0x43, 0x43, 0x75, 0xb8, 0x73, 0xa5, 0xd1,
	0x6a, 0xb5, 0x1c, 0xdb, 0x75, 0x8d, 0xc2, 0xce, 0x1f, 0x1a, 0x54, 0x2e, 0xcb, 0x81, 0xee, 0xc2,
	0xed, 0x7c, 0x93, 0xa5, 0xfe, 0x2e, 0x5f, 0x79, 0x0b, 0x6e, 0xce, 0x13, 0x5e, 0x58, 0x5e, 0xf3,
	0xc0, 0xd0, 0xd0, 0x1d, 0x30, 0xe7, 0x4d, 0x4f, 0xbe, 0xed, 0x36, 0x9f, 0x0b, 0x77, 0x0a, 0xa8,
	0x01, 0xb5, 0x79, 0xeb, 0xbe, 0x63, 0xdb, 0xaf, 0xa6, 0x0e, 0x15, 0x2f, 0xb9, 0x9c, 0x72, 0x6c,
	0xb7, 0xe9, 0x74, 0x5f, 0xf8, 0xfb, 0x87, 0x9d, 0x96, 0x6b, 0x94, 0xd0, 0x26, 0xdc, 0x9d, 0x67,
	0x38, 0xf6, 0x91, 0xed, 0x78, 0xbe, 0xe7, 0x58, 0x1d, 0x77, 0xdf, 0x76, 0x8c, 0xc5, 0x9d, 0x5f,
	0x34, 0x80, 0xe9, 0xeb, 0x46, 0x64, 0xa9, 0x69, 0xb9, 0xb6, 0xef, 0x7a, 0x96, 0x77, 0xe8, 0xce,
	0xc5, 0xb3, 0x01, 0xd7, 0x67, 0x8d, 0x3d, 0xbb, 0xd3, 0x6a, 0x77, 0x9e, 0x1a, 0x1a, 0x32, 0xe1,
	0xc6, 0xac, 0xc1, 0xea, 0xf5, 0x9c, 0xee, 0x91, 0xdd, 0x32, 0x0a, 0xf3, 0x16, 0xc7, 0x7e, 0x66,
	0x37, 0x3d, 0xbb, 0x65, 0x14, 0xe7, 0x2d, 0xf6, 0x4b, 0xbb, 0x79, 0x28, 0x2c, 0xa5, 0xf9, 0x6b,
	0x1c, 0xfb, 0xa8, 0xfb, 0xdc, 0x6e, 0x19, 0x8b, 0xf3, 0x06, 0xfb, 0x65, 0xaf, 0xed, 0xd8, 0x2d,
	0xa3, 0xbc, 0xc3, 0x00, 0xa6, 0x33, 0x5c, 0xc4, 0x70, 0xd4, 0xf5, 0x6c, 0xbf, 0xdb, 0xbb, 0x42,
	0x93, 0x0d, 0xb8, 0x3e, 0x6b, 0x4c, 0x5d, 0x35, 0x34, 0xb4, 0x0e, 0x68, 0xd6, 0xa0, 0x3c, 0x35,
	0x0a, 0x1f, 0x6c, 0x78, 0xe2, 0x7a, 0x56, 0xbb, 0x63, 0x14, 0x9f, 0x1c, 0xfc, 0x7a, 0x51, 0xd3,
	0xde, 0x5e, 0xd4, 0xb4, 0xbf, 0x2e, 0x6a, 0xda, 0x4f, 0xef, 0x6b, 0x0b, 0x6f, 0xdf, 0xd7, 0x16,
	0xde, 0xbd, 0xaf, 0x2d, 0xbc, 0xda, 0xed, 0xc7, 0xfc, 0x74, 0x7c, 0xbc, 0x1b, 0x92, 0xe1, 0x5e,
	0xd6, 0xd8, 0x7b, 0xd3, 0x8f, 0xfd, 0xb3, 0xe9, 0xe7, 0xbe, 0xfc, 0xd6, 0x3f, 0x2e, 0xcb, 0x8f,
	0xfd, 0xaf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x48, 0x2a, 0x38, 0x4c, 0x11, 0x0c, 0x00, 0x00,
}

func (m *AgentInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgentInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgentInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.LlmEndpointHash) > 0 {
		i -= len(m.LlmEndpointHash)
		copy(dAtA[i:], m.LlmEndpointHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LlmEndpointHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValidatorOperator) > 0 {
		i -= len(m.ValidatorOperator)
		copy(dAtA[i:], m.ValidatorOperator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ValidatorOperator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RiskReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RiskReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RiskReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubmitterSignature) > 0 {
		i -= len(m.SubmitterSignature)
		copy(dAtA[i:], m.SubmitterSignature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SubmitterSignature)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.EvidenceHash) > 0 {
		i -= len(m.EvidenceHash)
		copy(dAtA[i:], m.EvidenceHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EvidenceHash)))
		i--
		dAtA[i] = 0x62
	}
	if m.ExpiryHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.ObservedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ObservedHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Categories) > 0 {
		for iNdEx := len(m.Categories) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Categories[iNdEx])
			copy(dAtA[i:], m.Categories[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Categories[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if m.RiskScore != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RiskScore))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReportId) > 0 {
		i -= len(m.ReportId)
		copy(dAtA[i:], m.ReportId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ReportId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SanctionCase) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SanctionCase) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SanctionCase) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DecisionHash) > 0 {
		i -= len(m.DecisionHash)
		copy(dAtA[i:], m.DecisionHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DecisionHash)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.PolicyVersion) > 0 {
		i -= len(m.PolicyVersion)
		copy(dAtA[i:], m.PolicyVersion)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PolicyVersion)))
		i--
		dAtA[i] = 0x5a
	}
	if m.ExecutedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExecutedHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.VotingDeadlineHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VotingDeadlineHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.OpenedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OpenedHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.ReportIds) > 0 {
		for iNdEx := len(m.ReportIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ReportIds[iNdEx])
			copy(dAtA[i:], m.ReportIds[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.ReportIds[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.RequestedAction != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RequestedAction))
		i--
		dAtA[i] = 0x28
	}
	if m.TargetType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TargetType))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TargetAddress) > 0 {
		i -= len(m.TargetAddress)
		copy(dAtA[i:], m.TargetAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TargetAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SanctionVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SanctionVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SanctionVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x42
	}
	if m.SignedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SignedHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RationaleHash) > 0 {
		i -= len(m.RationaleHash)
		copy(dAtA[i:], m.RationaleHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RationaleHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ReasonCode) > 0 {
		i -= len(m.ReasonCode)
		copy(dAtA[i:], m.ReasonCode)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ReasonCode)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ApprovedAction != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ApprovedAction))
		i--
		dAtA[i] = 0x20
	}
	if m.Option != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Option))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActiveSanction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveSanction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveSanction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivatedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ActivatedHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.Action != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TargetAddress) > 0 {
		i -= len(m.TargetAddress)
		copy(dAtA[i:], m.TargetAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TargetAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FreezeRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FreezeRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FreezeRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	if m.FrozenHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.FrozenHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StateChangeHash) > 0 {
		i -= len(m.StateChangeHash)
		copy(dAtA[i:], m.StateChangeHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.StateChangeHash)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ResultMessage) > 0 {
		i -= len(m.ResultMessage)
		copy(dAtA[i:], m.ResultMessage)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ResultMessage)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ResultCode) > 0 {
		i -= len(m.ResultCode)
		copy(dAtA[i:], m.ResultCode)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ResultCode)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ExecutedHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExecutedHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Executor) > 0 {
		i -= len(m.Executor)
		copy(dAtA[i:], m.Executor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Executor)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TargetAddress) > 0 {
		i -= len(m.TargetAddress)
		copy(dAtA[i:], m.TargetAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TargetAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Action != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CaseId) > 0 {
		i -= len(m.CaseId)
		copy(dAtA[i:], m.CaseId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CaseId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AgentInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ValidatorOperator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LlmEndpointHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Active {
		n += 2
	}
	return n
}

func (m *RiskReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReportId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RiskScore != 0 {
		n += 1 + sovTypes(uint64(m.RiskScore))
	}
	if len(m.Categories) > 0 {
		for _, s := range m.Categories {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ObservedHeight != 0 {
		n += 1 + sovTypes(uint64(m.ObservedHeight))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovTypes(uint64(m.ExpiryHeight))
	}
	l = len(m.EvidenceHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SubmitterSignature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *SanctionCase) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TargetAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TargetType != 0 {
		n += 1 + sovTypes(uint64(m.TargetType))
	}
	if m.RequestedAction != 0 {
		n += 1 + sovTypes(uint64(m.RequestedAction))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	if len(m.ReportIds) > 0 {
		for _, s := range m.ReportIds {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.OpenedHeight != 0 {
		n += 1 + sovTypes(uint64(m.OpenedHeight))
	}
	if m.VotingDeadlineHeight != 0 {
		n += 1 + sovTypes(uint64(m.VotingDeadlineHeight))
	}
	if m.ExecutedHeight != 0 {
		n += 1 + sovTypes(uint64(m.ExecutedHeight))
	}
	l = len(m.PolicyVersion)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DecisionHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *SanctionVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Option != 0 {
		n += 1 + sovTypes(uint64(m.Option))
	}
	if m.ApprovedAction != 0 {
		n += 1 + sovTypes(uint64(m.ApprovedAction))
	}
	l = len(m.ReasonCode)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RationaleHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SignedHeight != 0 {
		n += 1 + sovTypes(uint64(m.SignedHeight))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ActiveSanction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TargetAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Action != 0 {
		n += 1 + sovTypes(uint64(m.Action))
	}
	if m.ActivatedHeight != 0 {
		n += 1 + sovTypes(uint64(m.ActivatedHeight))
	}
	return n
}

func (m *FreezeRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.FrozenHeight != 0 {
		n += 1 + sovTypes(uint64(m.FrozenHeight))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ExecutionRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CaseId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Action != 0 {
		n += 1 + sovTypes(uint64(m.Action))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TargetAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Executor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ExecutedHeight != 0 {
		n += 1 + sovTypes(uint64(m.ExecutedHeight))
	}
	l = len(m.ResultCode)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ResultMessage)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.StateChangeHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AgentInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgentInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgentInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorOperator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorOperator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LlmEndpointHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LlmEndpointHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RiskReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RiskReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RiskReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RiskScore", wireType)
			}
			m.RiskScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RiskScore |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Categories", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Categories = append(m.Categories, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObservedHeight", wireType)
			}
			m.ObservedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ObservedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceHash = append(m.EvidenceHash[:0], dAtA[iNdEx:postIndex]...)
			if m.EvidenceHash == nil {
				m.EvidenceHash = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitterSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubmitterSignature = append(m.SubmitterSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.SubmitterSignature == nil {
				m.SubmitterSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SanctionCase) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SanctionCase: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SanctionCase: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetType", wireType)
			}
			m.TargetType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetType |= SanctionTargetType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedAction", wireType)
			}
			m.RequestedAction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedAction |= SanctionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CaseStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportIds = append(m.ReportIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedHeight", wireType)
			}
			m.OpenedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingDeadlineHeight", wireType)
			}
			m.VotingDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedHeight", wireType)
			}
			m.ExecutedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecisionHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DecisionHash = append(m.DecisionHash[:0], dAtA[iNdEx:postIndex]...)
			if m.DecisionHash == nil {
				m.DecisionHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SanctionVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SanctionVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SanctionVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Option", wireType)
			}
			m.Option = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Option |= VoteOption(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApprovedAction", wireType)
			}
			m.ApprovedAction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApprovedAction |= SanctionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReasonCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReasonCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RationaleHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RationaleHash = append(m.RationaleHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RationaleHash == nil {
				m.RationaleHash = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedHeight", wireType)
			}
			m.SignedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveSanction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveSanction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveSanction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= SanctionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivatedHeight", wireType)
			}
			m.ActivatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FreezeRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FreezeRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FreezeRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenHeight", wireType)
			}
			m.FrozenHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FrozenHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaseId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaseId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= SanctionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedHeight", wireType)
			}
			m.ExecutedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateChangeHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateChangeHash = append(m.StateChangeHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StateChangeHash == nil {
				m.StateChangeHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
